branches:
  only:
    - master

language: erlang
otp_release:
  - 21.0
  - 20.3
  - 19.3
  - 18.3
install:
  - travis_retry rvm use 2.2.6 --install --binary --fuzzy
  - make install

script: make travis
